repos:
  - repo: local
    hooks:
      - id: ruff
        name: Fix
        entry: python -m ruff
        language: system
        args: [--fix]
        require_serial: true
        types: [python]

      - id: ruff
        name: Format
        entry: python -m ruff format
        language: system
        require_serial: true
        types: [python]