name: Main

on:
  - workflow_dispatch

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
      - run: |
          python -m pip install -r requirements.txt .
          python -m playwright install chromium
      - name: Scrape
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "${{ secrets.AWS_REGION }}"
          GMAPS_API_KEY: "${{ secrets.GMAPS_API_KEY }}"
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
          OPENAI_MODEL: "${{ vars.OPENAI_MODEL }}"
          DATA_PATH: "${{ vars.DATA_PATH }}"
          MAX_DETAIL_PAGES: "${{ vars.MAX_DETAIL_PAGES }}"
          TRAVEL_CONFIG: "${{ vars.TRAVEL_CONFIG }}"
          ROOT_URL: "${{ vars.ROOT_URL }}"
        run: scrapy crawl llm

  # deploy:
  #   # needs: scrape
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.11.8'
  #   - run: |
  #       python -m pip install -r requirements.txt
  #   - run: quarto render dashboard.qmd
  #   - run: rsconnect deploy shiny . --name janpalasek --title housing-gpt