name: Main

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '0 2 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
      - run: python -m pip install -r requirements.txt .
	    - run: python -m playwright install chromium
      - run: scrapy crawl llm

  deploy:
    # needs: scrape
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11.8'
    - run: python -m pip install -r requirements.txt
    - run: quarto render dashboard.qmd
    - run: rsconnect deploy shiny . --name janpalasek --title housing-gpt