name: Scrape

on:
  workflow_dispatch:
  schedule:
    # Runs at 5:00 UTC every day
    - cron: '0 5 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
      - run: |
          python -m pip install -r requirements.txt .
          python -m playwright install chromium
      - name: Scrape
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "${{ secrets.AWS_REGION }}"
          GMAPS_API_KEY: "${{ secrets.GMAPS_API_KEY }}"
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
          OPENAI_MODEL: "${{ vars.OPENAI_MODEL }}"
          DATA_DIR_PATH: "${{ vars.DATA_DIR_PATH }}"
          MAX_DETAIL_PAGES: "${{ vars.MAX_DETAIL_PAGES }}"
          TRAVEL_CONFIG: "${{ vars.TRAVEL_CONFIG }}"
          ROOT_URLS: "${{ vars.ROOT_URLS }}"
        run: scrapy crawl llm
  scrape-sreality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
      - run: |
          python -m pip install -r requirements.txt .
          python -m playwright install chromium
      - name: Scrape Sreality
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "${{ secrets.AWS_REGION }}"
          GMAPS_API_KEY: "${{ secrets.GMAPS_API_KEY }}"
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
          OPENAI_MODEL: "${{ vars.OPENAI_MODEL }}"
          DATA_DIR_PATH: "${{ vars.DATA_DIR_PATH }}"
          MAX_DETAIL_PAGES: "${{ vars.MAX_DETAIL_PAGES }}"
          TRAVEL_CONFIG: "${{ vars.TRAVEL_CONFIG }}"
          ROOT_URLS: "${{ vars.SREALITY_ROOT_URLS }}"
        run: scrapy crawl sreality